server:
  port: 9999

application:
  unidbg:
    dynarmic: false
    verbose: false
    async: false

spring:
    thymeleaf:
        prefix: classpath:/templates
        suffix: .html
        cache: false
    redis:
        host: localhost
        port: 6379
        password:
        database: 0

